# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: 2025 Erlang Ecosystem Foundation

name: "Test All CycloneDX Combinations"
description: "Tests all CycloneDX schema/format combinations for a given command"
inputs:
  command:
    description: "Command to generate SBoM (e.g., 'rebar3 sbom')"
    required: true
  command-args:
    description: "Additional arguments to append to the command (e.g., '.' for escript/burrito)"
    required: false
    default: ""
  test-name:
    description: "Name for the test (used in log file and output)"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Install CycloneDX CLI"
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        echo "PATH=$PATH" >> "$GITHUB_ENV"
        brew tap cyclonedx/cyclonedx
        brew install cyclonedx/cyclonedx/cyclonedx-cli
      shell: bash

    - name: "Test All Combinations"
      env:
        COMMAND: ${{ inputs.command }}
        COMMAND_ARGS: ${{ inputs.command-args }}
        TEST_NAME: ${{ inputs.test-name }}
      run: |
        LOG_FILE="${TEST_NAME,,}_test.log"
        FAILED=0
        
        echo "=== $TEST_NAME Smoke Tests ===" > "$LOG_FILE"
        echo "" >> "$LOG_FILE"
        
        for FORMAT in "json" "xml"; do
          echo "--- Testing format $FORMAT ---" >> "$LOG_FILE"
          OUTPUT_FILE="bom_${TEST_NAME,,}.$FORMAT"
          
          echo -n "Format $FORMAT: "
          
          # Generate SBoM
          if $COMMAND \
            --format "$FORMAT" \
            --output "$OUTPUT_FILE" \
            $COMMAND_ARGS >> "$LOG_FILE" 2>&1; then
            
            # Validate SBoM
            if cyclonedx validate --input-file "$OUTPUT_FILE" --input-format "$FORMAT" --fail-on-errors >> "$LOG_FILE" 2>&1; then
              echo "✓"
            else
              echo "✗"
              FAILED=1
            fi
          else
            echo "✗"
            FAILED=1
          fi
          
          rm -f "$OUTPUT_FILE"
          echo "" >> "$LOG_FILE"
        done
        
        if [ "$FAILED" -eq 1 ]; then
          echo ""
          echo "=== FAILURES DETECTED - Full Log ==="
          cat "$LOG_FILE"
          exit 1
        fi
      shell: bash
